network:
  version: 2
  ethernets:
    enp1s0:
      addresses: [10.10.50.31/24]
      nameservers:
        addresses: [10.10.50.1,8.8.8.8]
      routes:
        - to: default
          via: 10.10.50.1
